import React, { useState, useMemo, useEffect, useCallback } from 'react';
import type { AiState, Agent, Consensus, GroundingChunk, CodeReviewFinding } from '../types';
import { highlightBasic, escapeHtml } from '../utils/highlighter'; // Import shared highlighter utilities

/**
 * Determines the inline CSS styles for an AgentCard based on its status.
 * This provides immediate visual feedback on an neuron's state (e.g., pulsing when working, shaking on error).
 * @param {Agent} agent - The agent object containing status and color information.
 * @returns {React.CSSProperties} A style object to be applied to the agent card's container.
 */
const getAgentCardStyle = (agent: Agent): React.CSSProperties => {
    switch (agent.status) {
        case 'working':
            return {
                borderColor: agent.color,
                boxShadow: `0 0 20px ${agent.color}80, inset 0 0 10px ${agent.color}40`,
                animation: 'agentPulse 2s infinite ease-in-out',
            };
        case 'error':
            return {
                borderColor: '#EF4444', /* Red-500 */
                boxShadow: `0 0 15px #EF444499`,
                animation: 'agentError 0.5s linear',
            };
        case 'idle':
            return {
                borderColor: '#33363E', /* Darker border when idle */
                animation: 'none',
                opacity: 0.8,
            };
        case 'done':
            return {
                borderColor: agent.color,
                opacity: 1,
                boxShadow: `0 0 10px ${agent.color}40`,
            };
        default:
            return {
                borderColor: '#33363E',
            };
    }
};

/**
 * A UI component representing a single AI agent. It displays the agent's name,
 * subtitle, current status, and a status message or content. Visual styling is
 * dynamically applied based on the agent's status to provide clear feedback.
 * @param {{ agent: Agent }} props - Component props containing the agent data.
 * @returns {React.ReactElement} The rendered agent card element.
 */
const AgentCard: React.FC<{ agent: Agent }> = ({ agent }) => (
    <div
        className={`agent-card bg-panel rounded-lg p-3 mb-2 border-l-4 transition-all duration-300 shadow-md`}
        style={getAgentCardStyle(agent)}
    >
        <div
            className="agent-title font-bold text-sm mb-1"
            style={{ color: agent.status === 'error' ? '#EF4444' : agent.color }}
        >
            {agent.title}
        </div>
        <div className="agent-subtitle text-xs text-muted-text mb-1.5">{agent.subtitle}</div>
        <div className="agent-content text-xs min-h-[20px] flex items-center">
            {agent.status === 'working' && (
                <div className="quantum-spinner w-4 h-4 inline-block mr-1.5 relative">
                    <div className="absolute w-full h-full border-2 border-transparent border-t-agent-cognito rounded-full quantum-spinner::before"></div>
                    <div className="absolute w-full h-full border-2 border-transparent border-b-agent-nexus rounded-full quantum-spinner::after"></div>
                </div>
            )}
            {agent.status === 'done' && (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 mr-1.5 text-green-400 flex-shrink-0"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
            )}
            {agent.status === 'error' && (
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 mr-1.5 text-red-500 flex-shrink-0"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                    />
                </svg>
            )}
            {/* Detailed Status Message */}
            {typeof agent.content === 'string' ? (
                <span className="flex-1 truncate" title={agent.content}>
                    {agent.content}
                </span>
            ) : (
                <span className="flex-1">
                    {agent.content}
                </span>
            )}
        </div>
    </div>
);

/**
 * A panel that displays the results of a multi-agent consensus process.
 * It lists all the code candidates generated by the agents, highlighting the top-scoring
 * candidate and showing which agents contributed to each version.
 * @param {{ consensus: Consensus }} props - Component props containing the consensus result data.
 * @returns {React.ReactElement} The rendered consensus results panel.
 */
const ConsensusPanel: React.FC<{ consensus: Consensus }> = ({ consensus }) => (
    <div className="consensus-panel bg-panel rounded-lg p-3.5 mt-4 max-h-72 overflow-y-auto border border-agent-nexus shadow-lg">
        <div className="consensus-header font-bold text-agent-nexus mb-2.5 flex justify-between items-center text-base">
            <span>Multi-Agent Consensus Results</span>
            <span className="bg-agent-nexus text-white px-2 py-0.5 rounded-full text-xs font-normal">Score: {consensus.score}</span>
        </div>
        <div className="agent-list">
            {consensus.allCandidates.map((c, i) => (
                <div
                    key={i}
                    className={`candidate-item bg-white/10 rounded-md p-2.5 mb-2 border-l-4 transition-all duration-200 ${
                        i === 0 ? 'border-l-accent bg-accent/20 shadow-md' : 'border-l-agent-cognito hover:bg-white/15'
                    }`}
                >
                    <div className="text-xs text-muted-text flex justify-between mb-1.5">
                        <span className="font-semibold text-white/80">{c.agents.join(', ')}</span>
                        <span>Count: {c.count}</span>
                    </div>
                    <div className="text-xs font-mono whitespace-pre-wrap max-h-20 overflow-hidden text-ellipsis text-slate-300">
                        {c.content.substring(0, 200)}
                        {c.content.length > 200 ? '...' : ''}
                    </div>
                </div>
            ))}
        </div>
    </div>
);

/**
 * A panel that displays the web sources used for grounding a Gemini API response.
 * It lists the titles and links to the web pages that the AI used to formulate its answer,
 * providing transparency and allowing for source verification.
 * @param {{ chunks: GroundingChunk[] }} props - Component props containing the array of grounding chunks.
 * @returns {React.ReactElement} The rendered grounding sources panel.
 */
const GroundingPanel: React.FC<{ chunks: GroundingChunk[] }> = ({ chunks }) => {
    const webChunks = chunks.filter(chunk => chunk.web);
    const mapsChunks = chunks.filter(chunk => chunk.maps);

    if (webChunks.length === 0 && mapsChunks.length === 0) {
        return null; // Don't render if no grounding data
    }

    return (
        <div className="grounding-panel bg-yellow-900/20 border border-agent-relay rounded-lg p-3.5 mt-4 shadow-lg">
            <div className="flex items-center gap-2 font-bold text-agent-relay mb-3 text-base">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M10 3.5a1.5 1.5 0 01.5 2.915V9.5a1.5 1.5 0 01-3 0V6.415A1.5 1.5 0 0110 3.5z" />
                    <path d="M10 18a8 8 0 100-16 8 8 0 000 16zM2 10a8 8 0 1116 0 8 8 0 01-16 0z" />
                </svg>
                <span>Grounded Information</span>
            </div>

            {webChunks.length > 0 && (
                <div className="mb-4">
                    <h4 className="text-sm font-bold text-agent-relay mb-2">Google Search Results:</h4>
                    <ol className="list-decimal list-inside text-xs space-y-2 pl-1">
                        {webChunks.map((chunk, i) =>
                            chunk.web && (
                                <li key={`web-${i}`} className="truncate">
                                    <a
                                        href={chunk.web.uri}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        title={chunk.web.title || chunk.web.uri}
                                        className="text-sky-400 hover:underline hover:text-sky-300 transition-colors"
                                    >
                                        {chunk.web.title || chunk.web.uri}
                                    </a>
                                    {/* Removed chunk.web.snippet as per types.ts update */}
                                </li>
                            )
                        )}
                    </ol>
                </div>
            )}

            {mapsChunks.length > 0 && (
                <div>
                    <h4 className="text-sm font-bold text-agent-relay mb-2">Google Maps Results:</h4>
                    <ol className="list-decimal list-inside text-xs space-y-2 pl-1">
                        {mapsChunks.map((chunk, i) =>
                            chunk.maps && (
                                <li key={`maps-${i}`} className="truncate">
                                    <a
                                        href={chunk.maps.uri}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        title={chunk.maps.title || chunk.maps.uri}
                                        className="text-sky-400 hover:underline hover:text-sky-300 transition-colors"
                                    >
                                        {chunk.maps.title || chunk.maps.uri}
                                    </a>
                                    {chunk.maps.placeAnswerSources && chunk.maps.placeAnswerSources.length > 0 && (
                                        <div className="ml-4 mt-1 space-y-1">
                                            {chunk.maps.placeAnswerSources.map((source, j) => (
                                                <div key={`maps-source-${i}-${j}`}>
                                                  {/* FIX: `displayText` is a property of `reviewSnippets` items, not directly on `MapsPlaceAnswerSource`. */}
                                                    {source.reviewSnippets && source.reviewSnippets.length > 0 && (
                                                        <ul className="list-disc list-inside ml-2 text-slate-500 text-[0.6rem]">
                                                            {source.reviewSnippets.map((review, k) => (
                                                                review.uri && (
                                                                    <li key={`review-${i}-${j}-${k}`} className="line-clamp-2">
                                                                        <a
                                                                            href={review.uri}
                                                                            target="_blank"
                                                                            rel="noopener noreferrer"
                                                                            title={review.displayText}
                                                                            className="text-slate-400 hover:underline"
                                                                        >
                                                                            {review.displayText || 'Review link'}
                                                                        </a>
                                                                    </li>
                                                                )
                                                            ))}
                                                        </ul>
                                                    )}
                                                </div>
                                            ))}
                                        </div>
                                    )}
                                </li>
                            )
                        )}
                    </ol>
                </div>
            )}
        </div>
    );
};

/**
 * Generates a diff between two strings using a simplified LCS (Longest Common Subsequence) algorithm.
 * @param {string} oldStr The original string.
 * @param {string} newStr The new string.
 * @returns {Array<{type: 'common' | 'added' | 'removed', text: string}>} An array of diff objects.
 */
const generateDiff = (oldStr: string, newStr: string) => {
    const oldLines = oldStr.split('\n');
    const newLines = newStr.split('\n');
    const M = oldLines.length;
    const N = newLines.length;
    const dp = Array.from({ length: M + 1 }, () => Array(N + 1).fill(0));

    for (let i = 1; i <= M; i++) {
        for (let j = 1; j <= N; j++) {
            if (oldLines[i - 1] === newLines[j - 1]) {
                dp[i][j] = dp[i - 1][j - 1] + 1;
            } else {
                dp[i][j] = Math.max(dp[i - 1][j], dp[i][j - 1]);
            }
        }
    }

    const diff = [];
    let i = M,
        j = N;
    while (i > 0 || j > 0) {
        if (i > 0 && j > 0 && oldLines[i - 1] === newLines[j - 1]) {
            diff.unshift({ type: 'common' as const, text: oldLines[i - 1] });
            i--;
            j--;
        } else if (j > 0 && (i === 0 || dp[i][j - 1] >= dp[i - 1][j])) {
            diff.unshift({ type: 'added' as const, text: newLines[j - 1] });
            j--;
        } else if (i > 0 && (j === 0 || dp[i][j - 1] < dp[i - 1][j])) {
            diff.unshift({ type: 'removed' as const, text: oldLines[i - 1] });
            i--;
        } else {
            break;
        }
    }
    return diff;
};

/**
 * Highlights occurrences of a query within a text string by wrapping them in <mark> tags.
 * @param {string} text - The source text (e.g., a block of code).
 * @param {string} query - The search term to highlight.
 * @returns {string} An HTML string with matches highlighted.
 */
const highlightMatches = (text: string, query: string): string => {
    if (!query) return escapeHtml(text); // Use escapeHtml from highlighter.ts
    const escapedText = escapeHtml(text);
    const escapedQuery = query.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&');
    const regex = new RegExp(`(${escapedQuery})`, 'gi');
    return escapedText.replace(regex, `<mark class="bg-yellow-500/50 rounded px-0.5">$1</mark>`);
};

/**
 * A simple component to display a line-by-line diff.
 * @param {{ before: string; after: string; query?: string }} props - Component props.
 * @param {string} props.before - The original string content.
 * @param {string} props.after - The new string content.
 * @param {string} [props.query] - Optional search query to highlight within diff lines.
 * @returns {React.ReactElement} The rendered diff viewer.
 */
const DiffViewer: React.FC<{ before: string; after: string; query?: string }> = ({ before, after, query = '' }) => {
    const diff = useMemo(() => generateDiff(before, after), [before, after]);

    return (
        <pre className="text-xs font-mono whitespace-pre-wrap text-slate-300 bg-black/30 p-2 rounded custom-scrollbar">
            {diff.map((line, index) => (
                <div key={index} className={`flex items-center ${line.type === 'added' ? 'bg-green-900/40' : line.type === 'removed' ? 'bg-red-900/40' : ''}`}>
                    <span className={`w-4 text-center text-[0.6rem] flex-shrink-0 ${line.type === 'added' ? 'text-green-300' : line.type === 'removed' ? 'text-red-300' : 'text-gray-500'}`}>
                        {line.type === 'added' ? '+' : line.type === 'removed' ? '-' : ' '}
                    </span>
                    <code
                        className="flex-grow min-w-0"
                        dangerouslySetInnerHTML={{ __html: highlightMatches(line.text, query) }}
                    />
                </div>
            ))}
        </pre>
    );
};


/**
 * A panel that displays the results of an AI code review.
 * It lists all the findings from the AI, categorized by severity,
 * and provides actionable suggestions for each.
 * @param {{ findings: CodeReviewFinding[] }} props - Component props containing the array of review findings.
 * @returns {React.ReactElement} The rendered code review panel.
 */
const CodeReviewPanel: React.FC<{ findings: CodeReviewFinding[] }> = ({ findings }) => {
    const severityStyles = {
        Critical: {
            icon: 'M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z',
            color: 'text-red-400',
            borderColor: 'border-red-500',
        },
        Warning: {
            icon: 'M20.944 15.006L13.52 3.29A2 2 0 0011.808 2H12a2 2 0 00-1.789 1.144L2.981 15.14A2 2 0 004.69 18h14.62a2 2 0 001.634-2.994zM12 6a1 1 0 011 1v4a1 1 0 01-2 0V7a1 1 0 011-1zm1 9a1 1 0 11-2 0 1 1 0 012 0z',
            color: 'text-yellow-400',
            borderColor: 'border-yellow-500',
        },
        Suggestion: {
            icon: 'M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z',
            color: 'text-sky-400',
            borderColor: 'border-sky-500',
        },
    };

    if (findings.length === 0) {
        return (
            <div className="code-review-panel bg-panel rounded-lg p-3.5 mt-4 text-center border border-green-700 shadow-lg">
                <div className="flex items-center gap-2 justify-center font-bold text-green-400 mb-2 text-base">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                        <path
                            fillRule="evenodd"
                            d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                            clipRule="evenodd"
                        />
                    </svg>
                    <span>No issues found. Code looks great!</span>
                </div>
            </div>
        );
    }

    return (
        <div className="code-review-panel bg-panel rounded-lg p-3.5 mt-4 max-h-72 overflow-y-auto border border-agent-sentinel shadow-lg">
            <div className="flex items-center gap-2 font-bold text-agent-sentinel mb-3 text-base">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                >
                    <path
                        fillRule="evenodd"
                        d="M8.257 3.099c.765-1.3 2.647-1.3 3.412 0l7.288 12.414c.48 1.036-.263 2.148-1.442 2.148H2.492c-1.179 0-1.92-1.112-1.442-2.148L8.257 3.099zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z"
                        clipRule="evenodd"
                    />
                </svg>
                <span>AI Code Review Findings ({findings.length})</span>
            </div>

            <div className="flex flex-col gap-3">
                {findings.map((f, i) => {
                    const style = severityStyles[f.severity];
                    return (
                        <div
                            key={i}
                            className={`bg-white/5 rounded p-2 border-l-4 ${style.borderColor} shadow-sm`}
                        >
                            <div className="flex items-center gap-2 text-xs font-semibold mb-1">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    className={`h-4 w-4 ${style.color} flex-shrink-0`}
                                    fill="none"
                                    viewBox="0 0 24 24"
                                    stroke="currentColor"
                                >
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={style.icon} />
                                </svg>
                                <span className={style.color}>{f.severity}</span>
                                <span className="text-gray-400">|</span>
                                <span className="text-sky-300">{f.category}</span>
                                <span className="ml-auto text-gray-500">Line: {f.line_number}</span>
                            </div>
                            <p className="text-xs text-slate-300 ml-6">{f.suggestion}</p>
                        </div>
                    );
                })}
            </div>
        </div>
    );
};

interface AiResponsePanelProps {
    isOpen: boolean;
    aiState: AiState;
    onClose: () => void;
    onApplyCode: (code: string) => void;
    onCopyCode: (code: string) => void;
    originalCode: string;
}

/**
 * The main panel for displaying AI responses, including generated code,
 * multi-agent consensus results, and grounding sources. It provides actions
 * to apply the code to the editor or copy it to the clipboard.
 * @param {AiResponsePanelProps} props - The component props.
 * @returns {React.ReactElement | null} The rendered AI response panel or null if not open.
 */
export const AiResponsePanel: React.FC<AiResponsePanelProps> = ({
    isOpen,
    aiState,
    onClose,
    onApplyCode,
    onCopyCode,
    originalCode,
}) => {
    const { agents, isLoading, consensus, generatedCode, groundingChunks, codeReviewFindings } = aiState;

    // Filter out `nexus` and `echo` as they are orchestrating agents and not directly generating/contributing content.
    const displayAgents = useMemo(
        () => agents.filter((agent) => agent.name !== 'nexus' && agent.name !== 'echo'),
        [agents]
    );

    if (!isOpen) return null;

    const codeToDisplay = generatedCode || consensus?.selectedCandidate || '';
    const showDiff = !!generatedCode && !!originalCode;

    return (
        <div
            className="fixed inset-0 bg-black/60 flex items-center justify-center z-40 p-4 backdrop-blur-sm"
            onClick={onClose}
        >
            <div
                className="w-full max-w-4xl bg-panel border border-agent-nexus rounded-lg shadow-2xl flex flex-col max-h-[90vh] overflow-hidden"
                onClick={(e) => e.stopPropagation()}
            >
                <header className="p-4 border-b border-gray-700 flex justify-between items-center bg-header-bg">
                    <h2 className="text-lg font-bold text-white animation-title-pulse">Quantum AI Response</h2>
                    <button onClick={onClose} className="text-xl text-gray-400 hover:text-white transition-colors">
                        &times;
                    </button>
                </header>

                <div className="flex-1 p-4 overflow-y-auto custom-scrollbar">
                    <div className="agent-grid grid grid-cols-2 md:grid-cols-3 gap-3">
                        {displayAgents.map((agent) => (
                            <AgentCard key={agent.name} agent={agent} />
                        ))}
                    </div>

                    {isLoading && (
                        <div className="text-center text-lg text-agent-cognito mt-8 flex items-center justify-center gap-3">
                            <div className="quantum-spinner w-6 h-6 inline-block relative">
                                <div className="absolute w-full h-full border-2 border-transparent border-t-agent-cognito rounded-full quantum-spinner::before"></div>
                                <div className="absolute w-full h-full border-2 border-transparent border-b-agent-nexus rounded-full quantum-spinner::after"></div>
                            </div>
                            Processing Quantum Flux...
                        </div>
                    )}

                    {codeReviewFindings && codeReviewFindings.length > 0 && (
                        <CodeReviewPanel findings={codeReviewFindings} />
                    )}
                    {consensus && <ConsensusPanel consensus={consensus} />}
                    {groundingChunks && groundingChunks.length > 0 && (
                        <GroundingPanel chunks={groundingChunks} />
                    )}

                    {codeToDisplay && (
                        <div className="generated-code-section mt-6">
                            <h3 className="text-base font-bold text-agent-nexus mb-2 flex items-center gap-2">
                                <svg
                                    xmlns="http://www.w3.org/2000/svg"
                                    className="h-5 w-5"
                                    viewBox="0 0 20 20"
                                    fill="currentColor"
                                >
                                    <path
                                        fillRule="evenodd"
                                        d="M10 2a8 8 0 100 16 8 8 0 000-16zM2 10a8 8 0 1116 0 8 8 0 01-16 0zm9.293-2.293a1 1 0 00-1.414-1.414L9 8.586 7.707 7.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                        clipRule="evenodd"
                                    />
                                </svg>
                                Generated Code:
                            </h3>
                            <div className="relative bg-black/20 rounded-lg p-3 border border-white/10 shadow-inner">
                                {showDiff ? (
                                    <DiffViewer before={originalCode} after={codeToDisplay} />
                                ) : (
                                    <pre className="text-xs font-mono whitespace-pre-wrap text-slate-300 custom-scrollbar">
                                        <code dangerouslySetInnerHTML={{ __html: highlightBasic(codeToDisplay, 'js') }} />
                                    </pre>
                                )}
                            </div>
                        </div>
                    )}
                </div>

                <footer className="p-4 border-t border-gray-700 flex justify-end gap-2 bg-header-bg flex-shrink-0">
                    {codeToDisplay && (
                        <>
                            <button
                                onClick={() => onCopyCode(codeToDisplay)}
                                className="bg-agent-cognito hover:bg-emerald-400 text-black font-bold px-4 py-2 rounded-md transition-colors"
                            >
                                Copy Code
                            </button>
                            <button
                                onClick={() => onApplyCode(codeToDisplay)}
                                className="bg-success hover:bg-green-400 text-white font-bold px-8 py-2 rounded-md transition-colors"
                            >
                                Apply Code
                            </button>
                        </>
                    )}
                    <button
                        onClick={onClose}
                        className="bg-error hover:bg-red-600 text-white font-bold px-4 py-2 rounded-md transition-colors"
                    >
                        Close
                    </button>
                </footer>
            </div>
        </div>
    );
};